# Generated by Django 4.1.4 on 2022-12-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_user_profile_picture_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp_created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp_posted',
            new_name='timestamp_created',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
